=== NivekAlunya/csharp/semaine 8/Course/ConsoleApplication1/Menu.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Menu"
    targetNamespace="http://tempuri.org/Menu.xsd"
    elementFormDefault="qualified"
    xmlns="http://tempuri.org/Menu.xsd"
    xmlns:mstns="http://tempuri.org/Menu.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  
  <xs:element name="restaurant">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="menu" type="type-menu" minOccurs="1" maxOccurs="unbounded"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="menu-item">
      <xs:sequence>
        <xs:element name="name" type="type-name" minOccurs="1" maxOccurs="unbounded"></xs:element>
      </xs:sequence>
  </xs:complexType>

  <xs:complexType name="type-menu">
     <xs:sequence>
        <xs:element name="first-dish" type="menu-item"></xs:element>
        <xs:element name="main-dish" type="menu-item"></xs:element>
        <xs:choice>
          <xs:element name="cheese" type="menu-item"></xs:element>
          <xs:element name="dessert" type="menu-item"></xs:element>
        </xs:choice>
        <xs:element name="coffee" type="menu-item" minOccurs="0" maxOccurs="1"></xs:element>
        <xs:element name="liquor" type="menu-item" minOccurs="0" maxOccurs="1"></xs:element>
     </xs:sequence>
    <xs:attribute name="price" type="xs:integer" use="optional"></xs:attribute>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="gastronomic|cheap" ></xs:pattern>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="type-name">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="energy" type="xs:integer" use="required"></xs:attribute>
        <xs:attribute name="fruit" type="xs:string" use="optional"></xs:attribute>
        <xs:attribute name="savour" type="xs:string" use="optional"></xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>

=== NivekAlunya/csharp/Semaine 9/Course/ConsoleApplication1/Menu.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--DOCTYPE restaurant SYSTEM "Menu.dtd" -->
<!--DOCTYPE
  restaurant [
  <!ELEMENT restaurant (menu+)>
  <!ELEMENT menu (first-dish,main-dish,cheese?,dessert?,coffee?,liquor?)>
  <!ELEMENT first-dish (name+)>
  <!ELEMENT main-dish (name+)>
  <!ELEMENT cheese (name+)>
  <!ELEMENT coffee (name+)>
  <!ELEMENT liquor (name+)>
  <!ELEMENT dessert (name+)>
  <!ELEMENT name (#PCDATA)>
  <!ATTLIST menu 
    type (cheap|gastronomic) #REQUIRED
    price NMTOKEN #REQUIRED
  >
  <!ATTLIST name 
    energy NMTOKENS #REQUIRED
    savour (chocolate) #IMPLIED
    fruit (apricot) #IMPLIED
  >
]
-->
<!--  xmlns="http://tempuri.org/Menu.xsd"-->
<restaurant  xmlns="http://tempuri.org/Menu.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Menu.xsd">
  <menu type="gastronomic" price="60">
    <first-dish>
      <name energy="50">Radis</name>
      <name energy="450">Saucisson</name>
      <name energy="10">Salade verte</name>
    </first-dish>
    <main-dish>
      <name energy="150">Choucroute</name>
      <name energy="2500">Cassoulet</name>
      <name energy="1000">Couscous</name>
    </main-dish>
    <cheese>
      <name energy="1500">Camenbert</name>
      <name energy="150">Brie</name>
      <name energy="50">Roquefort</name>
    </cheese>
  </menu>
  <menu type="cheap">
    <first-dish>
      <name energy="50">Radis</name>
      <name energy="450">Saucisson</name>
      <name energy="10">Salade verte</name>
    </first-dish>
    <main-dish>
      <name energy="150">Choucroute</name>
      <name energy="2500">Cassoulet</name>
      <name energy="1000">Couscous</name>
    </main-dish>
    <dessert>
      <name energy="1500" savour="chocolate">Icecream</name>
      <name energy="150" fruit="apricot">Pie</name>
      <name energy="50">Roquefort</name>
    </dessert>
    <coffee>
      <name energy="250">irish coffee</name>
    </coffee>
    <liquor>
      <name energy="1000" savour="xxxxx">liquor</name>
    </liquor>
  </menu>
</restaurant>
